	<div id="formContainer">
    	<form action="" id="form" method="post">
    		<div>
    			Nome:<input type="text" id="name" name="name" /><span id="fieldname" style="display:none;"><ul></ul></span><br />
    		</div>
    		<div>
    			Username: <input type="text" id="username" name="username" /><span id="fieldusername" style="display:none;"><ul></ul></span><br />
    		</div>
    		<div>
    			Email:<input type="text" id="email" name="email" /><span id="fieldemail" style="display:none;"><ul></ul></span><br />
    		</div>
    		<button id="btnSalvar" type="button">Salvar</button>
    </form>
</div>